#!/bin/sh
# Copyright 2010-2011 Université Joseph Fourier
# 
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#  
#    http://www.apache.org/licenses/LICENSE-2.0
#  
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

natives=-Djava.library.path=natives/jni/MacOSX/

# if problems when discovering the philips HUE, enable the scanNetwork to true

java -Djava.util.logging.config.file=conf/logging.properties -Dlogback.configurationFile=conf/logback.xml ${natives} -jar bin/felix.jar
