/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appsgate.lig.eude.interpreter.langage.components;

import java.util.HashSet;
import java.util.Set;

/**
 *
 * @author jr
 */
public class Variable {

    private final String id;
    private final String type;

    /**
     * Constructor
     * 
     * @param i the id
     * @param t the type
     */
    public Variable(String i, String t) {
        this.id = i;
        this.type = t;
    }

    /**
     * Return the text which is used to build a text program from a program tree
     * @return 
     */
    public String getExpertProgramDecl() {
        return "{ type: " + this.type + ", id: " + this.id + "}";
    }

    /**
     * two variables are equals if they have the same id and type
     * @param other
     * @return true if both variables are the same
     */
    public boolean equals(Variable other) {
        return other.id.equals(this.id) && other.type.equals(this.type);
    }

    /**
     * Return the list of events of a variable
     * 
     * By default a variable can not throw any events
     * 
     * @return the events that can be generated by this variable
     */
    public Set<String> getEventList() {
        return null;
    }
    
    /**
     * Return the list of actions of a variable
     * 
     * By default a variable can not do any action
     * 
     * @return the actions that can be generated by this variable
     */
    public Set<String> getActionList() {
        return null;
    }
    
    /**
     * Return the list of states a variable can have
     * 
     * By default a variable has no states
     * 
     * @return the events that can be generated by this variable
     */
    public Set<String> getStateList() {
        return null;
    }
    
    /**
     * Return the list of types that has a variable
     * 
     * By default a variable is of type variable
     * 
     * @return the types contained by this variable
     */
    public Set<String> getTypes() {
        HashSet<String> ret = new HashSet<String>();
        ret.add(this.type);
        return ret;
    }

}
