#! /bin/sh
#--------------------------------------#
# /etc/rc.d/init.d/ubikit              #
#                                      #
#   Author: Lionel Balme, Immotronic   #
#   Date: 20 Juin 2012                 #
#   Version: 1.2.0                     #
#--------------------------------------#
#
#   Change logs:
#
#   1.2.0: 
#      - adding lock file remove at starting
#      - LED starting sequence enhancement
#      - renaming log files
#      - support the new PlaceTouch rootfs configuration
#
#   1.1.0: 
#      - Turn LEDs off before starting Ubikit and after stopping it.
#
#   1.0.0: Initial version
#---------------------------------------------

# Setting path
JAVAHOME=/opt/ejre1.6.0_27
JAVA=$JAVAHOME/bin/java
 
# Some things that run always
####touch /var/lock/ubikit

if [ -d /var/log/ubikit ]
  then continue
else
    mkdir /var/log/ubikit 
fi
 
# Carry out specific functions when asked to by the system
case "$1" in
  start)
#####    echo "## Starting Ubikit..."

#   Turn LED 1 red, Turn off LED 2
#####    echo -n 0 > /dev/j35pin3
#####    echo -n 1 > /dev/j35pin4
#####    echo -n 0 > /dev/j35pin5
#####    echo -n 0 > /dev/j35pin6

#####    cd /opt/ubikit
#####    rm -f ubikit_databases/apps/*.lck
#####    rm -f ubikit_databases/pems/*.lck
#####    rm -f ubikit_databases/system/*.lck
#####    $JAVA -jar bin/felix.jar > /var/log/ubikit/log 2> /var/log/ubikit/framework.log &
#	cd /opt/AppsGate-distribution 
#	$./apam
    ;;
  stop)
    echo "## Stopping Ubikit..."
    echo shutdown | telnet localhost 6666 

# 	Turn off LEDs
    echo -n 0 > /dev/j35pin3
    echo -n 0 > /dev/j35pin4
    echo -n 0 > /dev/j35pin5
    echo -n 0 > /dev/j35pin6
    ;;
  reset)
    echo "## Reseting Ubikit to factory default" 
    echo "## Stopping..."
    echo shutdown | telnet localhost 6666 
    
# 	Turn off LEDs
    echo -n 0 > /dev/j35pin3
    echo -n 0 > /dev/j35pin4
    echo -n 0 > /dev/j35pin5
    echo -n 0 > /dev/j35pin6
    echo "...[WAITING]..."
    sleep 2 s
    echo "## Clearing caches, logs & db..."
    rm -R /opt/ubikit/ubikit_databases
    rm -R /opt/ubikit/felix-cache
    rm /var/log/ubikit/*
    echo "## Starting..."
#   Turn LED 1 red, Turn off LED 2
    echo -n 0 > /dev/j35pin3		
    echo -n 1 > /dev/j35pin4
    echo -n 0 > /dev/j35pin5
    echo -n 0 > /dev/j35pin6
    
    cd /opt/ubikit
    $JAVA -jar bin/felix.jar > /var/log/ubikit/log 2> /var/log/ubikit/framework.log &
    ;;
  *)
    echo "Usage: /etc/rc.d/init.d/ubikit {start | stop | reset }"
    echo "-------------------------------------------"
	echo "  * start: Start the Ubikit framework"
	echo "  * stop:  Stop the Ubikit framework"
	echo "  * reset: Stop, then reset the framework to factory default, then restart it"
	echo
    exit 1
    ;;
esac
 
exit 0
